# Generated by Django 5.1.7 on 2025-03-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_alter_aboutme_id_alter_contact_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
