# Generated by Django 5.1.7 on 2025-03-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_delete_page_aboutme_resume_project_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_images/')),
            ],
        ),
    ]
