# Generated by Django 5.1.7 on 2025-03-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'About Me', 'verbose_name_plural': 'About Me'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Home'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Project'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skill'},
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='resume',
        ),
        migrations.AddField(
            model_name='home',
            name='hire_me_link',
            field=models.URLField(default='#contact'),
        ),
        migrations.AddField(
            model_name='home',
            name='resume_link',
            field=models.URLField(default='#about'),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
