# Generated by Django 5.1.7 on 2025-03-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_alter_aboutme_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
