# Generated by Django 5.1.7 on 2025-03-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_home_name_alter_home_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='hire_me_link',
            field=models.URLField(default='#contact'),
        ),
    ]
