# Generated by Django 5.1.7 on 2025-03-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0009_aboutme_hire_me_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home_images/'),
        ),
    ]
