# Generated by Django 5.1.7 on 2025-03-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_testimony_delete_contactinfo_alter_aboutme_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'About Me', 'verbose_name_plural': 'About Me'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Home'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Project'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skill'},
        ),
        migrations.AlterModelOptions(
            name='testimony',
            options={'verbose_name': ' Testimony', 'verbose_name_plural': ' Testimony'},
        ),
    ]
