# Generated by Django 5.1.7 on 2025-03-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0013_alter_aboutme_id_alter_contact_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
