# Generated by Django 5.1.7 on 2025-03-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0014_delete_contactinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimony',
            options={'verbose_name': ' InfoOfSite', 'verbose_name_plural': ' InfoOfSite'},
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='role',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='text',
        ),
    ]
