# Generated by Django 5.1.7 on 2025-03-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0015_alter_testimony_options_remove_testimony_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images/'),
        ),
    ]
