# Generated by Django 5.1.7 on 2025-03-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0017_aboutme_description_color_aboutme_hire_me_link_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='menu_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
